version: '3'
services:
  music-api:
    container_name: inethi-music-share-api
    build: ./
    restart: always
    links:
      - music-mariadb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.musicshareapi.rule=Host(`${TRAEFIK_API_RULE_MUSICSHARE_API}`)"
      - "traefik.http.routers.musicshareapi.entrypoints=${TRAEFIK_ENTRYPOINT}"

  music-wordpress:
    image: wordpress:latest
    container_name: inethi-musicshare-wordpress
    volumes:
      - "${MUSIC_SHARE_WORDPRESS_MOUNT}:/var/www/html"
      - "${MUSIC_SHARE_WORDPRESS_MOUNT_INI_FILE}:/usr/local/etc/php/conf.d/uploads.ini"
      - "${MUSIC_SHARE_WORDPRESS_MOUNT_CONTENT_FOLDER}:/var/www/html/wp-content"
    environment:
      - "WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}"
      - "WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}"
      - "WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}"
      - "WORDPRESS_DB_USER=${WORDPRESS_DB_USER}"
      - "WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}"
    depends_on:
      - music-mariadb
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.musicshare.rule=Host(`${TRAEFIK_API_RULE_MUSICSHARE}`)"
      - "traefik.http.routers.musicshare.entrypoints=${TRAEFIK_ENTRYPOINT}"

  music-mariadb:
    image: mariadb/server:10.4
    container_name: inethi-musicshare-mariadb
    volumes:
      - "${MUSIC_SHARE_MARIADB_MOUNT}:/var/lib/mysql"
    environment:
      - "MYSQL_ROOT_PASSWORD=${WORDPRESS_DB_PASSWORD}"
      - "MYSQL_USER=${WORDPRESS_DB_USER}"
      - "MYSQL_PASSWORD=${WORDPRESS_DB_PASSWORD}"
      - "MYSQL_DATABASE=${WORDPRESS_DB_NAME}"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.musicsharemariadb.rule=Host(`${TRAEFIK_API_RULE_MARIADB}`)"
      - "traefik.http.routers.musicsharemariadb.entrypoints=${TRAEFIK_ENTRYPOINT}"

  music-adminer:
    image: adminer
    container_name: inethi-musicshare-adminer
    restart: always
    links:
      - music-mariadb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`${TRAEFIK_API_RULE_ADMINER}`)"
      - "traefik.http.routers.adminer.entrypoints=${TRAEFIK_ENTRYPOINT}"

networks:
  default:
    external:
      name: "${INETHI_NETWORK}"
